# Generated by Django 5.0 on 2023-12-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='Маргарита', max_length=255),
            preserve_default=False,
        ),
    ]
