# Generated by Django 5.0 on 2024-01-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_userprofile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_articles',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='liked_posts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
